# Generated by Django 3.2.16 on 2022-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikus', '0002_alter_haiku_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='content',
            field=models.TextField(help_text='Write haiku here'),
        ),
        migrations.AlterField(
            model_name='haiku',
            name='title',
            field=models.CharField(help_text='Enter a title', max_length=100, unique=True),
        ),
    ]
