# Generated by Django 3.2.16 on 2022-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikus', '0003_auto_20221107_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='haiku',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
