# Generated by Django 3.2.16 on 2022-11-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikus', '0004_auto_20221107_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='haiku',
            name='tag',
            field=models.CharField(default='Other', max_length=80),
        ),
    ]
