# Generated by Django 3.2.16 on 2022-11-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikus', '0005_auto_20221108_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='tag',
            field=models.CharField(default='Tag haiku appropriately', max_length=80),
        ),
    ]
